baseurl = "/"
languageCode = "en"
title = "Amit Adhikari"
theme = "etch"
copyright = "&copy; <a href=\"https://github.com/adkri\">Amit Adhikari</a> 2020"
disqusShortname = "adhikari-me"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true
enableEmoji = true
disablePathToLower = true
preserveTaxonomyNames=true
pygmentsUseClasses=true
pygmentsCodeFences = true

[params]
  description = "Personal blog of Amit Adhikari"
  # copyright = "Copyright © 2020 Amit Adhikari"
  dark = "off"
  highlight = true

[params.sections_right]
"/about" = "About"
# "/projects" = "Projects"

[params.sections_left]
"/" = "Posts"
"/tags" = "Tags"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Amit Adhikari" # Title for home page
poweredby = false # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "amitadkri"
github = "adkri"
email = ""
linkedin = "amit-adhikari"
instagram = ""
facebook = ""
codepen = ""

[params.matomoAnalytics]
siteID = 1
rootURL = "//"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
