baseurl = "/"
languageCode = "en"
title = "Amit Adhikari"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/adkri\">Amit Adhikari</a> 2018"
disqusShortname = "adkri"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

[params.sections_right]
"/about" = "About"
"/projects" = "Projects"

[params.sections_left]
"/" = "Posts"
"/tags" = "Tags"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "amitadk"
github = "adkri"
email = "end.adhikai@gmail.com"
linkedin = "amitadhikari"
facebook = "end.adhikari"
instagram = "amitadk"
codepen = ""

[params.matomoAnalytics]
siteID = 1
rootURL = "//matomo.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
